
SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;

-- # 실습 문제
-- 1. employees, departments 테이블을 INNER JOIN해서
-- FIRST_NAME, DEPARTMENT_ID, DEPARTMENT_NAME을 조회하세요.

SELECT
    E.FIRST_NAME, E.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY E.DEPARTMENT_ID;


-- 2. employees, departments 테이블을 NATURAL JOIN해서
-- FIRST_NAME, DEPARTMENT_ID, DEPARTMENT_NAME을 조회하세요.

SELECT
    E.FIRST_NAME, DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E 
NATURAL JOIN DEPARTMENTS D;
-- MANAGER_ID, DEPARTMENT_ID가 모두 겹치는 것을 찾으므로 결과값이 32개 밖에 안 나옴.

-- USING절 사용
SELECT
    E.FIRST_NAME, DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E 
JOIN DEPARTMENTS D USING (DEPARTMENT_ID); -- 결과값 정상적으로 106개 나옴

SELECT
    E.FIRST_NAME, DEPARTMENT_ID, D.DEPARTMENT_NAME, MANAGER_ID
FROM EMPLOYEES E
JOIN DEPARTMENTS D USING (DEPARTMENT_ID, MANAGER_ID);


-- 3. employees, departments 테이블을 JOIN ON을 사용해서
-- FIRST_NAME, DEPARTMENT_ID, DEPARTMENT_NAME을 조회하세요.

SELECT
    E.FIRST_NAME, E.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E
JOIN DEPARTMENTS D 
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;
